os: linux
language: c
install:
    - git clone -b devel --depth 1 git://github.com/Araq/Nim.git
    - (cd Nim && sh ci/build.sh && ./koch nimble)
    - export PATH=`pwd`/Nim/bin:$PATH
script:
    make
